// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tBN7QNNjbfqB4C-QF6gn0dp6iDtaj80',
    appId: '1:272354970674:web:0cd45ef4e210e7afd6402b',
    messagingSenderId: '272354970674',
    projectId: 'chatapp-d0507',
    authDomain: 'chatapp-d0507.firebaseapp.com',
    storageBucket: 'chatapp-d0507.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSm7B_NWeT8GXWGQPABFKtQ0zrIB0QhKk',
    appId: '1:272354970674:android:62eb539f0b35ac31d6402b',
    messagingSenderId: '272354970674',
    projectId: 'chatapp-d0507',
    storageBucket: 'chatapp-d0507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hrmIzJ30lH_Y55m_m6S3N2Ohab4zzXY',
    appId: '1:272354970674:ios:f8d14ea339655f4fd6402b',
    messagingSenderId: '272354970674',
    projectId: 'chatapp-d0507',
    storageBucket: 'chatapp-d0507.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hrmIzJ30lH_Y55m_m6S3N2Ohab4zzXY',
    appId: '1:272354970674:ios:f8d14ea339655f4fd6402b',
    messagingSenderId: '272354970674',
    projectId: 'chatapp-d0507',
    storageBucket: 'chatapp-d0507.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4tBN7QNNjbfqB4C-QF6gn0dp6iDtaj80',
    appId: '1:272354970674:web:ea9b1fa3580328dbd6402b',
    messagingSenderId: '272354970674',
    projectId: 'chatapp-d0507',
    authDomain: 'chatapp-d0507.firebaseapp.com',
    storageBucket: 'chatapp-d0507.appspot.com',
  );
}
